[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "coherencecalculator"
version = "1.0.0"
description = "Calculate coherence scores of speech."
readme = "README.md"
requires-python = ">=3.12,<3.14"
license = { file = "LICENSE.txt" }
authors = [
    { name = "WeizheXu", email = "xuweizhe@uw.edu" },
]
dependencies = [
    "en-core-web-sm",
    "fastapi[standard]>=0.141.1",
    "gensim>=4.4.0",
    "huggingface-hub>=0.36.2",
    "importlib-metadata>=9.0.0",
    "nltk>=3.10.2",
    "numba-cuda>=0.30.4",
    "pandas==2.2.3",
    "scipy==1.14.0",
    "semvecpy>=0.1.26",
    "sentence-transformers>=5.7.0",
    "simcse",
    "spacy>=3.8.15",
    "torch>=2.11.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.26.0",
    "transformers==4.47.0",
    "tsfresh>=0.21.2",
]

[tool.setuptools]
package-dir = { "" = "src" }
packages = [
    "coherencecalculator",
    "coherencecalculator.diffcse",
    "coherencecalculator.pipelines",
    "coherencecalculator.scripts",
    "coherencecalculator.simcse",
    "coherencecalculator.tools",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchaudio = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
en-core-web-sm = { url = "http://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
simcse = { git = "https://github.com/YongsenTan/SimCSE.git" }
